name: Build and deploy Node.js app to Azure Web App - tech0-gen8-step4-pos-app-36

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 全履歴を取得

      - name: Debug project structure
        run: ls -R

      - name: Check if package.json exists
        run: |
          if [ ! -f package.json ]; then
            echo "Error: package.json not found"
            exit 1
          else
            echo "package.json found!"
          fi

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: .

      - name: Remove node_modules to reduce artifact size
        run: rm -rf node_modules

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "node_modules/*" ".git/*" ".github/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tech0-gen8-step4-pos-app-36'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4549173A91E24C328C727EE9B2AD1098 }}

      - name: Clean up artifact
        run: rm -f release.zip
